name: Deploy game to Netlify

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  GODOT_VERSION: 4.4

# Allow one concurrent deployment
concurrency:
  group: "game-deployment"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.4
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
          cache: "npm"

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Setup Godot
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Godot Web Build
        run: |
          mkdir -v -p exports/web
          godot --headless --verbose --export-release "Web" "exports/web/index.html"

      - name: Deploy to Netlify
        run: netlify deploy --dir=exports/web --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

    #   - name: Deploy production to Netlify
    #     uses: nwtgck/actions-netlify@v2.1.0
    #     with:
    #       publish-dir: "./exports/web"
    #       github-token: ${{ secrets.GITHUB_TOKEN }}
    #       deploy-message: "Testing workflow"
    #       production-deploy: true
    #     env:
    #       NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
    #       NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
