name: Deploy game to GitHub Pages 2

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

env:
  GODOT_VERSION: 4.4
  EXPORT_PATH: exports/web
  EXPORT_NAME: Web

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-22.04
    container:
      image: barichello/godot-ci:4.4
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Godot Web Build
        run: |
          mkdir -v -p ${EXPORT_PATH}
          godot --headless --verbose --export-release "${EXPORT_NAME}" "${EXPORT_PATH}/index.html"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ${{ env.EXPORT_PATH }} # The folder the action should deploy.
