name: Deploy game to Netlify

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "game-deployment"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Install Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: "4.4.0"
          export-templates: true
          use-dotnet: false

      - name: Check Godot version
        run: godot --version

      - name: Download export templates
        run: godot -v --download-export-templates

      - name: Export HTML5
        run: |
          mkdir -p exports/web
          godot --headless --export-release "Web" exports/web/index.html

      - name: Deploy production to Netlify
        uses: nwtgck/actions-netlify@v2.1.0
        with:
          publish-dir: "./exports/web"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Testing workflow"
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
